"""
Single source of truth for CFTC market names used in TFF / disagg loaders and downstream SQL.

Must match `Market_and_Exchange_Names` in CFTC files — edit here only, then run cftc_loader.
"""
from __future__ import annotations

# SOFR 3M (TFF) — same string as in CFTC com_fin_txt reports
SOFR_3M_TFF_FULL_NAME = "SOFR-3M - CHICAGO MERCANTILE EXCHANGE"

FIN_STRICT: tuple[str, ...] = (
    "USD INDEX - ICE FUTURES U.S.",
    "EURO FX - CHICAGO MERCANTILE EXCHANGE",
    "BRITISH POUND - CHICAGO MERCANTILE EXCHANGE",
    "JAPANESE YEN - CHICAGO MERCANTILE EXCHANGE",
    "CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE",
    "SWISS FRANC - CHICAGO MERCANTILE EXCHANGE",
    "AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE",
    "NZ DOLLAR - CHICAGO MERCANTILE EXCHANGE",
    "BITCOIN - CHICAGO MERCANTILE EXCHANGE",
    "ETHER CASH SETTLED - CHICAGO MERCANTILE EXCHANGE",
    "E-MINI S&P 500 - CHICAGO MERCANTILE EXCHANGE",
    "NASDAQ MINI - CHICAGO MERCANTILE EXCHANGE",
    "RUSSELL E-MINI - CHICAGO MERCANTILE EXCHANGE",
    "NIKKEI STOCK AVERAGE - CHICAGO MERCANTILE EXCHANGE",
    "VIX FUTURES - CBOE FUTURES EXCHANGE",
    "UST 2Y NOTE - CHICAGO BOARD OF TRADE",
    "UST 10Y NOTE - CHICAGO BOARD OF TRADE",
    "UST BOND - CHICAGO BOARD OF TRADE",
    "FED FUNDS - CHICAGO BOARD OF TRADE",
    SOFR_3M_TFF_FULL_NAME,
)

DIS_STRICT: tuple[str, ...] = (
    "GOLD - COMMODITY EXCHANGE INC.",
    "SILVER - COMMODITY EXCHANGE INC.",
    "COPPER- #1 - COMMODITY EXCHANGE INC.",
    "WTI-PHYSICAL - NEW YORK MERCANTILE EXCHANGE",
)
